project:
  type: book
  
execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "Policy Analysis in the New York Legislative Environment"
  subtitle: "Hands-on Approach"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - planning.qmd
    - intro.qmd
    - part: "Policy Analysis"
      chapters:    
      - policy_analysis.qmd    
    - part: "The Issue"
      chapters:    
      - issue.qmd
    - part: "The Bill"
      chapters:          
      - bill.qmd
      - research.qmd
      - legislative_history.qmd
    - part: "Who the Bill Would Affect and How"
      chapters:    
      - impacts.qmd
    - part: "Legal Issues"
      chapters:
      - legal.qmd
    - part: "Implementation"      
      chapters:
      - implementation.qmd
    - part: "Fiscal Impact"
      chapters:
      - fiscal.qmd
    - part: "Alternative Approaches"
      chapters:
      - alternatives.qmd
    - part: "What Finally Happened to A.4454 of 2024?"      
    - part: "Presentation"
      chapters:
      - presentation.qmd
    - part: "Appendices"
      chapters:    
      - appendix/resources.qmd
      - appendix/askquestion.qmd
    - part: "Notes"
      chapters:
      - notes/gce_links.qmd
      - notes/identify_advocacy_organizations.qmd
      - notes/housing_advocacy_organizations.qmd
      - notes/landlord_advocacy_organizations.qmd
      - notes/gce_proposed_vs_enacted.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: 5
    toc-depth: 5
    toc-expand: false
  # pdf:
  #   documentclass: scrreprt

# editor: console or visual

editor_options:
  chunk_output_type: console

# useful reminders of quarto commands:
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt 
# quarto publish quarto-pub --no-render

# possibly use this at start of each doc??
# ---
# output: html_document
# editor_options:
#   chunk_output_type: console
# ---
