project:
  type: book
  
execute:
  eval: true
  echo: true
  output: true
  freeze: false  # auto: during global project renders, re-render only when source changes

book:
  title: "Examine PUF-Policy Engine files"
  subtitle: "Multiple years"
  # author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - planning.qmd
    # - intro.qmd
    # - issue.qmd
    # - bill.qmd
    # - legislative_history.qmd
    # - part: "Revenue options"
    #   chapters:
    #   - options/summary.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  # pdf:
  #   documentclass: scrreprt

# editor: console or visual

editor_options:
  chunk_output_type: console

# useful reminders of quarto commands:
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt 
# quarto publish quarto-pub --no-render

# possibly use this at start of each doc??
# ---
# output: html_document
# editor_options:
#   chunk_output_type: console
# ---
